---
- name: Update web servers
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
    - name: node node architecture
      ansible.builtin.blockinfile:
        create: yes
        path: /root/facts.txt
        block: |
          Ansible managed node architecture is {{ ansible_architecture }}
    - name: Install Apache Webserver
      yum: pkg=httpd state=latest
    - name: Enable Apache on system reboot
      service: name=httpd enabled=yes
      notify: restart apache
    - name: Copy facts.txt to index.html
      shell: |
        cp /root/facts.txt /var/www/html/index.html      
  handlers:
    - name: restart apache
      service: name=httpd  state=restarted