apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lemp-wp
  name: lemp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: lemp-wp
  type: NodePort
status:
  loadBalancer: {}
