version: '2'
services:
    web:
        image: app
        container_name: python
        build: 
          context: ./app
        ports:
            - "5000:5000"
        volumes:
            - ./app:/code
        depends_on:
            - redis_app
    redis_app:
        image: redis
        container_name: redis