apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- iron-namespace-nautilus.yaml
- iron-db-deployment-nautilus.yaml
- iron-gallery-deployment-nautilus.yaml
- iron-db-service-nautilus.yaml
- iron-gallery-service-nautilus.yaml
