apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-phpfpm
  name: nginx-phpfpm
spec:
  volumes:
  - name: shared-files
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
      name: nginx-config
      items:
        - path: nginx.conf
          key: nginx.conf
  containers:
  - image: nginx:latest
    name: nginx-container 
    resources: {}
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  - name: php-fpm-container
    image:  php:7.3-fpm-alpine
    volumeMounts:
    - mountPath: /var/www/html
      name: shared-files
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
