---
- name: Update web servers
  hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: Create a symbolic link
    ansible.builtin.file:
      src: /opt/security
      dest: /var/www/html
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: link
  - name: Touch again the same file,
    ansible.builtin.file:
       path: /opt/security/blog.txt
       state: touch
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: u+rw,g-wx,o-rwx
       modification_time: preserve
       access_time: preserve
    when: inventory_hostname == "stapp01"
  - name: Touch again the same file,
    ansible.builtin.file:
       path: /opt/security/story.txt
       state: touch
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: u+rw,g-wx,o-rwx
       modification_time: preserve
       access_time: preserve
    when: inventory_hostname == "stapp02"
  - name: Touch again the same file,
    ansible.builtin.file:
       path: /opt/security/media.txt
       state: touch
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: u+rw,g-wx,o-rwx
       modification_time: preserve
       access_time: preserve
    when: inventory_hostname == "stapp03"