apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql-db-url.yml
- mysql-pv-claim.yml
- mysql-pv.yml
- mysql-root-pass.yml
- mysql-user-pass.yml
- mysql.yml
- mysql-deployment.yml